### PR TITLE
half-precision float supporting

### PR DESCRIPTION
**Pull request by soloice**
Hi, thanks for your contribution to this great repo. 
Though, I need to process half-precision float (or float16) in my own project. Finally, I added fp16 support to the repo.
Hope it could help more people like me.

### CODE REVIEW

**Comment by rogersce** [comment]
Thanks for figuring this out! I merged a pul request a few days ago, it looks like your changes undo this. Do you mind trying to rebase your changes on the latest version of master to keep these changes? I can also try to do this tmr if you not get a chance. Thanks!

**Comment by soloice** [comment]
Fine, I'll do it in a day or two.
Waiting for my new modification~

**Comment by soloice** [comment]
After I moved to your newly merged code, I met several problems with Eigen.....
I'm still debugging and trying to figure out what's happening.

**Comment by rancheng** [comment]
> After I moved to your newly merged code, I met several problems with `Eigen` (I load numpy array with `cnpy`, then convert it into `Eigen` matrix).....
> I'm still debugging and trying to figure out what's happening.

Hi @soloice, thanks for your contribution, we are now trying to load cnpy array into eigen matrix, are you able to finally figure out the eigen loader? if not, we are going to try overload the malloc function and create a wrapper for it.

**Comment by soloice** [comment]
@rancheng I managed to convert an older version of `cnpy` to `Eigen`, but not the current version. I didn't figure out why the incompatibility occurs and used an older version of `cnpy` in my personal project.
If you are to load `cnpy` array into `Eigen`, I think it would be better to rewrite it with malloc.

**Pull request closed without merging**
